# Generated by Django 2.1.7 on 2019-03-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_title',
            field=models.CharField(default='Hola', max_length=50),
            preserve_default=False,
        ),
    ]
