# Generated by Django 2.1.7 on 2019-03-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.CharField(default='Lorem Ipsum', max_length=5000),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Post Title Placeholder', max_length=50),
        ),
    ]
